# Generated by Django 3.1.1 on 2020-12-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201212_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_name',
        ),
    ]
